import { useEffect, useMemo, useState } from 'react';

export type Locale = 'en' | 'ru' | 'he' | 'de' | 'es';

export const localeMeta: Record<Locale, { label: string; dir: 'ltr'|'rtl'; nativeName: string }> = {
  en: { label: 'EN', dir: 'ltr', nativeName: 'English' },
  ru: { label: 'RU', dir: 'ltr', nativeName: 'Русский' },
  he: { label: 'עב', dir: 'rtl', nativeName: 'עברית' },
  de: { label: 'DE', dir: 'ltr', nativeName: 'Deutsch' },
  es: { label: 'ES', dir: 'ltr', nativeName: 'Español' },
};

const base: Record<string, string> = {
  appTitle: 'Sacred Breath',
  pranayamaPractice: 'PRANAYAMA PRACTICE',
  currentPhase: 'Current phase',
  start: 'Start', pause: 'Pause', resume: 'Resume', reset: 'Reset',
  endSession: 'End session', startSession: 'Start session',
  timer: 'Timer', guidance: 'Guidance',
  remaining: 'Remaining', cycle: 'Cycle', of: 'of', cycles: 'Cycles',
  inhale: 'Inhale', hold: 'Hold', exhale: 'Exhale', pausePhase: 'Rest',
  wolfActive: 'Active Breathing', wolfRest: 'Rest Phase',
  'guidance.inhale':     'Breathe in softly',
  'guidance.hold':       'Hold gently',
  'guidance.exhale':     'Breathe out slowly',
  'guidance.pause':      'Rest quietly',
  'guidance.wolfActive': 'Breathe rapidly and fully',
  'guidance.wolfRest':   'Deep rest — relax completely',
  'nav.home': 'Home', 'nav.session': 'Session',
  'nav.history': 'History', 'nav.analytics': 'Analytics', 'nav.dana': 'Dana',
  settings: 'Settings', sessionAtmosphere: 'SESSION ATMOSPHERE',
  settingsSaved: 'Selections are saved and apply as soon as you close the panel.',
  done: 'Done', breathingPractice: 'Breathing practice',
  meditationTone: 'Meditation tone',
  selectingMusicPreview: 'Selecting a track previews about 5 seconds.',
  selectingTonePreview: 'Selecting a tone previews about 2 seconds.',
  language: 'Language', volume: 'Volume',
  musicVolume: 'Music volume', toneVolume: 'Tone volume',
  musicToggle: 'Music', toneToggle: 'Tones', on: 'On', off: 'Off',
  level: 'Level', sessionDuration: 'Session duration', minutes: 'min',
  theme: 'Theme', themeAurora: 'Aurora', themeDark: 'Dark',
  selectPractice: 'Select practice', sessionOverview: 'Session overview',
  energyPattern: 'Energy pattern', cycleCount: 'Cycles',
  // 7 practices
  'practice.falcon.name':   'Falcon Breath',
  'practice.falcon.desc':   'Swift, energizing — rapid inhale, sharp exhale.',
  'practice.bear.name':     'Bear Breath',
  'practice.bear.desc':     'Deep, grounding — slow and powerful.',
  'practice.wolf.name':     'Wolf Breath',
  'practice.wolf.desc':     'Intense active cycles followed by deep rest.',
  'practice.turtle.name':   'Turtle Breath',
  'practice.turtle.desc':   'Extremely slow — deep peace and longevity.',
  'practice.square.name':   'Square Breathing',
  'practice.square.desc':   'Four equal sides — clarity and balance.',
  'practice.triangle.name': 'Triangle Breathing',
  'practice.triangle.desc': 'Extended hold for deep stillness.',
  'practice.orbit.name':    'Microcosmic Orbit',
  'practice.orbit.desc':    'Cyclical Qigong — continuous energy orbit.',
  // music / sounds
  'music.tibetan':        'Tibetan Bowls',
  'music.ambientYoga':    'Ambient Yoga',
  'music.himalayanBowls': 'Himalayan Bowls',
  'music.deepPranayama':  'Deep Pranayama',
  'sound.softBell':        'Soft Bell',
  'sound.woodenClick':     'Wooden Click',
  'sound.lightChime':      'Light Chime',
  'sound.tibetanMiniBowl': 'Tibetan Bowl',
  'sound.earthDrone':      'Earth Drone',
  // levels
  'level.beginner':     'Beginner',
  'level.intermediate': 'Intermediate',
  'level.advanced':     'Advanced',
  'level.master':       'Master',
  // energy
  'energy.default':          'Descending inhale',
  'energy.microcosmicOrbit': 'Continuous orbit',
  'energy.nadiShodhana':     'Ascending inhale',
  // complete / history / analytics / dana
  sessionComplete: 'Session Complete',
  sessionCompleteText: 'Let the resonance settle. You\'ve done well.',
  backToHome: 'Back to home',
  audioReady: 'Audio is ready for music, phase tones, and the session ending bell.',
  history: 'History', totalSessions: 'Sessions', totalMinutes: 'Minutes', streak: 'Streak',
  recentSessions: 'Recent sessions', clearHistory: 'Clear',
  noSessionsYet: 'No sessions yet. Begin your practice.',
  analyticsTitle: 'Analytics', analyticsCompleted: 'Completed',
  analyticsTotalTime: 'Total time', analyticsAverage: 'Average',
  analyticsMostUsed: 'Most used', analyticsSessions: 'sessions',
  analyticsPhases: 'Phase breakdown', analyticsProgress: 'By practice',
  analyticsTrends: 'Recent',
  danaTitle: 'Dana & Support',
  danaText: 'If this practice supports you, offer Dana to help sustain it.',
  danaButton: 'Offer Dana',
  'dana.paypal': 'PayPal', 'dana.whatsapp': 'WhatsApp', 'dana.telegram': 'Telegram',
  breathe: 'breathe', wolfCycle: 'Cycle',
  wolfActiveLabel: 'Active breathing', wolfRestLabel: 'Rest phase',
};

const overrides: Partial<Record<Locale, Record<string, string>>> = {
  ru: {
    pranayamaPractice: 'ПРАНАЯМА ПРАКТИКА',
    currentPhase: 'Текущая фаза',
    start: 'Начать', pause: 'Пауза', resume: 'Продолжить', reset: 'Сброс',
    endSession: 'Завершить', startSession: 'Начать',
    timer: 'Таймер', guidance: 'Гайданс', cycle: 'Цикл', of: 'из', cycles: 'Циклы',
    inhale: 'Вдох', hold: 'Задержка', exhale: 'Выдох', pausePhase: 'Пауза',
    wolfActive: 'Активное дыхание', wolfRest: 'Фаза отдыха',
    'guidance.inhale': 'Дышите медленно', 'guidance.hold': 'Задержите',
    'guidance.exhale': 'Выдохните медленно', 'guidance.pause': 'Отдохните',
    'guidance.wolfActive': 'Дышите быстро и полно', 'guidance.wolfRest': 'Глубокий отдых',
    'nav.home': 'Главная', 'nav.session': 'Сессия', 'nav.history': 'История',
    'nav.analytics': 'Аналитика', 'nav.dana': 'Дана',
    settings: 'Настройки', sessionAtmosphere: 'АТМОСФЕРА', done: 'Готово',
    breathingPractice: 'Практика', meditationTone: 'Тон медитации',
    language: 'Язык', musicVolume: 'Музыка', toneVolume: 'Тоны', on: 'Вкл', off: 'Выкл',
    level: 'Уровень', sessionDuration: 'Длительность', minutes: 'мин',
    theme: 'Тема', themeAurora: 'Аврора', themeDark: 'Тёмная',
    selectPractice: 'Выбор практики', cycleCount: 'Циклы',
    'practice.falcon.name': 'Дыхание сокола',
    'practice.bear.name':   'Дыхание медведя',
    'practice.wolf.name':   'Дыхание волка',
    'practice.turtle.name': 'Дыхание черепахи',
    'practice.square.name': 'Квадратное дыхание',
    'practice.triangle.name': 'Треугольное дыхание',
    'practice.orbit.name':  'Микрокосмическая орбита',
    'music.tibetan': 'Тибетские чаши', 'music.ambientYoga': 'Амбиент йога',
    'music.himalayanBowls': 'Гималайские чаши', 'music.deepPranayama': 'Глубокий пранаяма',
    'sound.softBell': 'Мягкий колокол', 'sound.tibetanMiniBowl': 'Тибетская чаша',
    'level.beginner': 'Начальный', 'level.intermediate': 'Средний',
    'level.advanced': 'Продвинутый', 'level.master': 'Мастер',
    sessionComplete: 'Сессия завершена', backToHome: 'На главную',
    audioReady: 'Аудио готово.',
    history: 'История', totalSessions: 'Сессий', totalMinutes: 'Минут', streak: 'Серия',
    recentSessions: 'Последние', clearHistory: 'Очистить', noSessionsYet: 'Сессий пока нет.',
    danaTitle: 'Дана и Поддержка', danaText: 'Поддержите практику.',
    breathe: 'дышите', wolfActiveLabel: 'Активное дыхание', wolfRestLabel: 'Фаза отдыха',
  },
  he: {
    pranayamaPractice: 'תרגול פראניאמה', currentPhase: 'שלב נוכחי',
    start: 'התחל', pause: 'השהה', resume: 'המשך', reset: 'איפוס',
    endSession: 'סיים', startSession: 'התחל',
    timer: 'טיימר', guidance: 'הדרכה', cycle: 'מחזור', of: 'מתוך', cycles: 'מחזורים',
    inhale: 'שאיפה', hold: 'עצירה', exhale: 'נשיפה', pausePhase: 'מנוחה',
    wolfActive: 'נשימה אקטיבית', wolfRest: 'שלב מנוחה',
    'guidance.inhale': 'נשמו בעדינות', 'guidance.hold': 'עצרו',
    'guidance.exhale': 'נשפו לאט', 'guidance.pause': 'נוחו',
    'guidance.wolfActive': 'נשמו מהר ומלא', 'guidance.wolfRest': 'מנוחה עמוקה',
    'nav.home': 'בית', 'nav.session': 'סשן', 'nav.history': 'היסטוריה',
    'nav.analytics': 'אנליטיקה', 'nav.dana': 'דאנה',
    settings: 'הגדרות', sessionAtmosphere: 'אווירת סשן', done: 'סיום',
    breathingPractice: 'תרגול נשימה', meditationTone: 'צליל',
    language: 'שפה', musicVolume: 'מוזיקה', toneVolume: 'צלילים', on: 'פועל', off: 'כבוי',
    level: 'רמה', sessionDuration: 'משך', minutes: 'דק',
    theme: 'ערכת נושא', themeAurora: 'ארורה', themeDark: 'כהה',
    selectPractice: 'בחר תרגול', cycleCount: 'מחזורים',
    'practice.falcon.name': 'נשימת הנץ',
    'practice.bear.name':   'נשימת הדוב',
    'practice.wolf.name':   'נשימת הזאב',
    'practice.turtle.name': 'נשימת הצב',
    'practice.square.name': 'נשימה מרובעת',
    'practice.triangle.name': 'נשימה משולשת',
    'practice.orbit.name':  'מסלול מיקרוקוסמי',
    'level.beginner': 'מתחיל', 'level.intermediate': 'בינוני',
    'level.advanced': 'מתקדם', 'level.master': 'מאסטר',
    sessionComplete: 'הסשן הושלם', backToHome: 'חזרה',
    audioReady: 'אודיו מוכן.',
    history: 'היסטוריה', totalSessions: 'סשנים', totalMinutes: 'דקות', streak: 'רצף',
    recentSessions: 'אחרונים', clearHistory: 'נקה', noSessionsYet: 'עדיין אין סשנים.',
    danaTitle: 'דאנה ותמיכה', danaText: 'הציעו דאנה.',
    breathe: 'נשמו', wolfActiveLabel: 'נשימה אקטיבית', wolfRestLabel: 'שלב מנוחה',
  },
  de: {
    pranayamaPractice: 'PRANAYAMA PRAXIS', currentPhase: 'Aktuelle Phase',
    start: 'Start', pause: 'Pause', resume: 'Fortsetzen', reset: 'Zurücksetzen',
    endSession: 'Beenden', startSession: 'Starten',
    timer: 'Timer', guidance: 'Führung', cycle: 'Zyklus', of: 'von', cycles: 'Zyklen',
    inhale: 'Einatmen', hold: 'Halten', exhale: 'Ausatmen', pausePhase: 'Pause',
    wolfActive: 'Aktives Atmen', wolfRest: 'Ruhephase',
    'guidance.inhale': 'Sanft einatmen', 'guidance.hold': 'Sanft halten',
    'guidance.exhale': 'Langsam ausatmen', 'guidance.pause': 'Ruhig verweilen',
    'guidance.wolfActive': 'Schnell und voll atmen', 'guidance.wolfRest': 'Tiefe Ruhe',
    'nav.home': 'Start', 'nav.session': 'Session', 'nav.history': 'Verlauf',
    'nav.analytics': 'Analyse', 'nav.dana': 'Dana',
    settings: 'Einstellungen', sessionAtmosphere: 'ATMOSPHÄRE', done: 'Fertig',
    breathingPractice: 'Atemübung', meditationTone: 'Meditationston',
    language: 'Sprache', musicVolume: 'Musik', toneVolume: 'Töne', on: 'An', off: 'Aus',
    level: 'Stufe', sessionDuration: 'Dauer', minutes: 'Min',
    theme: 'Thema', themeAurora: 'Aurora', themeDark: 'Dunkel',
    selectPractice: 'Praxis wählen', cycleCount: 'Zyklen',
    'practice.falcon.name': 'Falkenatmung',
    'practice.bear.name':   'Bärenatmung',
    'practice.wolf.name':   'Wolfatmung',
    'practice.turtle.name': 'Schildkrötenatmung',
    'practice.square.name': 'Quadratische Atmung',
    'practice.triangle.name': 'Dreiecks-Atmung',
    'practice.orbit.name':  'Mikrokosm. Umlaufbahn',
    'level.beginner': 'Anfänger', 'level.intermediate': 'Mittelstufe',
    'level.advanced': 'Fortgeschritten', 'level.master': 'Meister',
    sessionComplete: 'Session beendet', backToHome: 'Zurück',
    audioReady: 'Audio bereit.',
    history: 'Verlauf', totalSessions: 'Sessions', totalMinutes: 'Minuten', streak: 'Serie',
    recentSessions: 'Letzte', clearHistory: 'Löschen', noSessionsYet: 'Noch keine Sessions.',
    danaTitle: 'Dana & Unterstützung', danaText: 'Biete Dana an.',
    breathe: 'atmen', wolfActiveLabel: 'Aktives Atmen', wolfRestLabel: 'Ruhephase',
  },
  es: {
    pranayamaPractice: 'PRÁCTICA DE PRANAYAMA', currentPhase: 'Fase actual',
    start: 'Iniciar', pause: 'Pausar', resume: 'Continuar', reset: 'Reiniciar',
    endSession: 'Terminar', startSession: 'Iniciar',
    timer: 'Temporizador', guidance: 'Guía', cycle: 'Ciclo', of: 'de', cycles: 'Ciclos',
    inhale: 'Inhalar', hold: 'Retener', exhale: 'Exhalar', pausePhase: 'Descanso',
    wolfActive: 'Respiración activa', wolfRest: 'Fase de descanso',
    'guidance.inhale': 'Inhala suavemente', 'guidance.hold': 'Retén con calma',
    'guidance.exhale': 'Exhala despacio', 'guidance.pause': 'Descansa',
    'guidance.wolfActive': 'Respira rápido y profundo', 'guidance.wolfRest': 'Descansa completamente',
    'nav.home': 'Inicio', 'nav.session': 'Sesión', 'nav.history': 'Historial',
    'nav.analytics': 'Análisis', 'nav.dana': 'Dana',
    settings: 'Ajustes', sessionAtmosphere: 'ATMÓSFERA', done: 'Listo',
    breathingPractice: 'Práctica', meditationTone: 'Tono',
    language: 'Idioma', musicVolume: 'Música', toneVolume: 'Tonos', on: 'Sí', off: 'No',
    level: 'Nivel', sessionDuration: 'Duración', minutes: 'min',
    theme: 'Tema', themeAurora: 'Aurora', themeDark: 'Oscuro',
    selectPractice: 'Elegir práctica', cycleCount: 'Ciclos',
    'practice.falcon.name': 'Aliento del Halcón',
    'practice.bear.name':   'Aliento del Oso',
    'practice.wolf.name':   'Aliento del Lobo',
    'practice.turtle.name': 'Aliento de la Tortuga',
    'practice.square.name': 'Respiración Cuadrada',
    'practice.triangle.name': 'Respiración Triangular',
    'practice.orbit.name':  'Órbita Microcósmica',
    'level.beginner': 'Principiante', 'level.intermediate': 'Intermedio',
    'level.advanced': 'Avanzado', 'level.master': 'Maestro',
    sessionComplete: 'Sesión completa', backToHome: 'Inicio',
    audioReady: 'Audio listo.',
    history: 'Historial', totalSessions: 'Sesiones', totalMinutes: 'Minutos', streak: 'Racha',
    recentSessions: 'Recientes', clearHistory: 'Limpiar', noSessionsYet: 'Sin sesiones aún.',
    danaTitle: 'Dana y Apoyo', danaText: 'Ofrece Dana.',
    breathe: 'respira', wolfActiveLabel: 'Respiración activa', wolfRestLabel: 'Fase de descanso',
  },
};

const STORAGE_KEY = 'sb-locale';

export function useLocalization() {
  const [locale, setLocaleRaw] = useState<Locale>(() => {
    const s = localStorage.getItem(STORAGE_KEY);
    return (s && s in localeMeta) ? s as Locale : 'en';
  });

  const setLocale = (l: Locale) => { setLocaleRaw(l); localStorage.setItem(STORAGE_KEY, l); };

  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir  = localeMeta[locale].dir;
  }, [locale]);

  const t = useMemo(() => {
    const map = { ...base, ...(overrides[locale] ?? {}) };
    return (key: string): string => map[key] ?? base[key] ?? key;
  }, [locale]);

  return { locale, setLocale, t, dir: localeMeta[locale].dir, locales: localeMeta };
}
